sscs-10146 update sscs-common RC version
hmcts/sscs-ccd-callback-orchestrator pull request #858
Opened 2022-04-05 10:48 UTC by suetlaiHMCTS

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/SSCS-10146

### Change description ###
Update sscs-common version for ticket 10146

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-04-20 11:53 UTC, wmarshid approved these changes

2022-04-20 11:59 UTC, MohammedHMCTS requested changes

2022-04-20 11:59 UTC, MohammedHMCTS commented on build.gradle
> +    dependencySet(group: 'org.springframework', version: '5.2.20.RELEASE') {
Please remove this stuff and use the one in master

2022-04-20 11:59 UTC, MohammedHMCTS commented on config/owasp/suppressions.xml
> +   logback package
Please also remove these and use the one in master

2022-04-21 10:10 UTC, MohammedHMCTS approved these changes

2022-04-22 11:15 UTC, merged